module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "easy1.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 31 }, 
				textureRect = { x = 0, y = 0, width = 48, height = 31 }, 
				spriteSourceSize = { width = 48, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "easy2.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 31 }, 
				textureRect = { x = 50, y = 0, width = 48, height = 31 }, 
				spriteSourceSize = { width = 48, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "easy3.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 31 }, 
				textureRect = { x = 100, y = 0, width = 48, height = 31 }, 
				spriteSourceSize = { width = 48, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "easy4.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 31 }, 
				textureRect = { x = 150, y = 0, width = 48, height = 31 }, 
				spriteSourceSize = { width = 48, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "easy5.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 31 }, 
				textureRect = { x = 200, y = 0, width = 48, height = 31 }, 
				spriteSourceSize = { width = 48, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "easy6.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 31 }, 
				textureRect = { x = 250, y = 0, width = 48, height = 31 }, 
				spriteSourceSize = { width = 48, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium00.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 300, y = 0, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium01.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 352, y = 0, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium02.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 404, y = 0, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium03.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 456, y = 0, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium04.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 0, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium05.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 52, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium06.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 104, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium07.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 156, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium08.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 208, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium09.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 260, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium10.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 312, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "medium11.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 39 }, 
				textureRect = { x = 364, y = 41, width = 50, height = 39 }, 
				spriteSourceSize = { width = 50, height = 39 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "touch00.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 29 }, 
				textureRect = { x = 416, y = 41, width = 48, height = 29 }, 
				spriteSourceSize = { width = 48, height = 29 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "touch01.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 30 }, 
				textureRect = { x = 0, y = 82, width = 48, height = 30 }, 
				spriteSourceSize = { width = 48, height = 30 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "touch02.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 32 }, 
				textureRect = { x = 50, y = 82, width = 48, height = 32 }, 
				spriteSourceSize = { width = 48, height = 32 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "touch03.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 35 }, 
				textureRect = { x = 100, y = 82, width = 45, height = 35 }, 
				spriteSourceSize = { width = 45, height = 35 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch00.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 37 }, 
				textureRect = { x = 147, y = 82, width = 52, height = 37 }, 
				spriteSourceSize = { width = 52, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch01.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 37 }, 
				textureRect = { x = 201, y = 82, width = 56, height = 37 }, 
				spriteSourceSize = { width = 56, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch02.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 37 }, 
				textureRect = { x = 259, y = 82, width = 66, height = 37 }, 
				spriteSourceSize = { width = 66, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch03.png",
				spriteColorRect = { x = 0, y = 0, width = 73, height = 37 }, 
				textureRect = { x = 327, y = 82, width = 73, height = 37 }, 
				spriteSourceSize = { width = 73, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch04.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 37 }, 
				textureRect = { x = 402, y = 82, width = 66, height = 37 }, 
				spriteSourceSize = { width = 66, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch05.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 37 }, 
				textureRect = { x = 0, y = 121, width = 56, height = 37 }, 
				spriteSourceSize = { width = 56, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch06.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 37 }, 
				textureRect = { x = 58, y = 121, width = 52, height = 37 }, 
				spriteSourceSize = { width = 52, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch07.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 37 }, 
				textureRect = { x = 112, y = 121, width = 52, height = 37 }, 
				spriteSourceSize = { width = 52, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch08.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 37 }, 
				textureRect = { x = 166, y = 121, width = 52, height = 37 }, 
				spriteSourceSize = { width = 52, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch09.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 37 }, 
				textureRect = { x = 220, y = 121, width = 56, height = 37 }, 
				spriteSourceSize = { width = 56, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch10.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 37 }, 
				textureRect = { x = 278, y = 121, width = 66, height = 37 }, 
				spriteSourceSize = { width = 66, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch11.png",
				spriteColorRect = { x = 0, y = 0, width = 73, height = 37 }, 
				textureRect = { x = 346, y = 121, width = 73, height = 37 }, 
				spriteSourceSize = { width = 73, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch12.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 37 }, 
				textureRect = { x = 421, y = 121, width = 66, height = 37 }, 
				spriteSourceSize = { width = 66, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch13.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 37 }, 
				textureRect = { x = 0, y = 160, width = 56, height = 37 }, 
				spriteSourceSize = { width = 56, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch14.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 37 }, 
				textureRect = { x = 58, y = 160, width = 52, height = 37 }, 
				spriteSourceSize = { width = 52, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "very-touch15.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 37 }, 
				textureRect = { x = 112, y = 160, width = 52, height = 37 }, 
				spriteSourceSize = { width = 52, height = 37 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end